---
layout:        post
title:         "Python3 | no module named'_bz2'"
subtitle:      "Ubuntu 环境下 Python3 解决 modulenotfounderror: no module named '_bz2' "
author:        "Haauleon"
header-img:    "img/in-post/post-python/bg.jpeg"
header-mask:   0.4
catalog:       true
tags:
    - Python
---

### 异常信息
python3.9.15 调用 pandas 遇到错误提示：            
```
Traceback (most recent call last):
  File "export.py", line 40, in <module>
    from models.common import Conv
  File "/workspace/yolov5-v6/models/common.py", line 13, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.6/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 57, in <module>
    from pandas.core.aggregation import (
  File "/usr/local/lib/python3.6/site-packages/pandas/core/aggregation.py", line 27, in <module>
    from pandas.core.series import FrameOrSeriesUnion, Series
  File "/usr/local/lib/python3.6/site-packages/pandas/core/series.py", line 68, in <module>
    from pandas.core import algorithms, base, generic, nanops, ops
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 102, in <module>
    from pandas.io.formats import format as fmt
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/format.py", line 71, in <module>
    from pandas.io.common import stringify_path
  File "/usr/local/lib/python3.6/site-packages/pandas/io/common.py", line 3, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

这是因为从终端安装 python3 版本时，最新版本的 python3.9+ 缺少这个文件。需要手动添加。       

<br>
<br>

### 异常解决
1、在终端执行以下命令         
```bash
$ sudo apt-get install libbz2-dev
```

2、然后进入 Python3 的安装目录，重新编译 Python3     
```bash
$ cd Python-3.9.15
$ sudo ./configure --enable-optimozations
$ sudo make -j8
$ sudo make install
```

3、验证方法就是进入 python3 环境，看是否能导入 bz2 模块       
```bash
$ python3
>>> import bz2
```


<br>
<br>

---

相关链接：    
[Ubuntu下Python3解决modulenotfounderror: no module named '_bz2'](https://blog.csdn.net/wuyy0224/article/details/128168988)